# gitlab scanning
include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
 DAST_WEBSITE: $WEBSITE

dast:
  before_script:
    - echo "$WEBSITE" > environment_url.txt

# node docker image on which this would be run
image: node:12.2.0

stages:
  - test
  - deploy
  - dast

# builds app
build:
  stage: test
  script:
    - npm install
  tags:
    - docker

# deploys app to Staging 
deployToStaging:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  when: manual
