# node docker image on which this would be run
image: node:12.2.0

stages:
  - build
  - deploy

# builds app
build:
  stage: build
  script:
    - npm install
  tags:
    - docker

# deploys app to QA
deployToQA:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  when: manual